config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  
  resources :plants, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]  
    resources :plant_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :plant_comments, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  
  def index
    @user = current_user
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @plants = @user.plants.order(created_at: :desc).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to plants_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="container">
  <div class="row justify-center">
    <div class="mx-auto col-10">  
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>
              <h4>image</h4>
            </th>
            <th>
              <h4>name</h4>
            </th>
            <th colspan="3"></th>
          </tr>
        </thead> 
        <tbody> 
          <% users.each do |user| %> 
          <tr>
           <th><%= link_to user_path(user) do %>
                 <%= image_tag user.get_profile_image(75,75), class:"rounded-circle mg-fluid" %>
               <% end %>
           </th>
           <th><%= link_to user.name, user_path(user), class:"text-dark" %></th>
           <th>フォロー数: <%= user.followings.count %></th>
           <th>フォロワー数: <%= user.followers.count %></t>
           <th><%= render "relationships/btn", user: user %></th>
           <th><%= link_to "Users", users_path %></th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
      <div class="form-body p-4">
        <div class="mx-auto text-center">
            </div>
        <%= form_with model: @user do |f| %>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-user"></i></span>
            </div>
            <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputPassword", placeholder:"名前" %>
          </div>
          <div class="input-group mb-3" >
            <div class="mx-auto text-center rounded-circle">
            <%= image_tag @user.get_profile_image(100,100), class:"rounded-circle"; %>  
            </div>
          </div>  
            <div><%= f.file_field :profile_image, accept: "image/*", class: "w-100" %></div>    
          
          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-outline-primary mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'list', users: @users %>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-around">
    <div class="col-10">
      <table class="table table-borderless">
        
        <thead>
          <tr>
            <th>
              <h4>image</h4>
            </th>
            <th>
              <h4>name</h4>
            </th>
            <th></th>
          </tr>
        </thead>  
        
        <tbody>
          <tr>
      
            <th><%= link_to users_path do %>
              <%= image_tag @user.get_profile_image(70,70), class:"rounded-circle" %>
                <% end %>
            </th>
            <th><%= link_to @user.name, users_path, class:"text-dark" %></th>
          <% if @user == current_user %>
            <th><%= link_to "プロフィール編集", edit_user_path(@user), class:"btn btn-outline-primary" %></th>
            <th><%= link_to "退会", user_path(@user), method: :delete, "data-confirm" => "Are you sure you want to delete?", class:"btn btn-outline-danger" %></th>
          <% end %>
      
            <th>
              <td>
                <% if @user == current_user %>
                <% if current_user.following?(@user) %>
                  <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class:"btn btn-outline-info" %>
               <% else %>
                  <%= link_to 'フォローする', user_relationships_path(@user.id), method: :post, class:"btn btn-outline-success" %>
               <% end %>
                <% end %>
              </td>
            </th>
          
            <th>follows</th>
              <td><%= link_to @user.followings.count, user_followings_path(@user) %></td>
            </th>
            
            <th>followers
              <td><%= link_to @user.followers.count, user_followers_path(@user) %></td>
            </th>
            
          </tr>  
       </tbody>
       
      </table>
    </div>
  </div>
</div>
<div><%= render 'plants/list', plants: @plants %></div>