config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  
  resources :plants, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]  
    resources :plant_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plant.rb
class Plant < ApplicationRecord
    
  has_one_attached :image
  belongs_to :user
  has_many :plant_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :plant_name, presence: true
  validates :image, presence: true
  
  def get_image
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg')
       image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     image
  end 
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  
  def self.search_for(content, method)
    if method == 'perfect'
      Plant.where(plant_name: content)
    elsif method == 'forward'
      Plant.where('plant_name LIKE ?', content+'%')
    elsif method == 'backward'
      Plant.where('plant_name LIKE ?', '%' + content)
    else
      Plant.where('plant_name LIKE ?', '%' + content + '%')
    end
  end
  
  validates :plant_name,presence:true
  validates :caption,presence:true,length:{ maximum:200}
  
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
before_action :ensure_correct_user, only: [:update, :destroy] 

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user_id = current_user.id
    if @plant.save
       flash[:notice] = "You have created plant successfully."  
       redirect_to plants_path
    else
       render :new
    end  
  end
  
  def index
    @plants = Plant.order(created_at: :desc).page(params[:page])
  end

  def show
    @plant = Plant.find(params[:id])
    @plant_comment = PlantComment.new
  end
  
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    flash[:notice] = "plant was successfully destroyed."
    redirect_to plants_path
  end
  
  private

  def plant_params
    params.require(:plant).permit(:plant_name, :image, :caption)
  end
  
  def ensure_correct_user
    @plant = Plant.find(params[:id])
    unless @plant.user == current_user
      redirect_to plants_path
    end
  end
  
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_list.html.erb
<div class="container">
  <div class="row">
  <% plants.each do |plant| %>
    <div class="col-ms-auto">
      <div class="card mx-1 mt-1 shadow-lg" style="width: 370px;">
      <%= link_to plant_path(plant.id) do %>
        <%= image_tag plant.get_image, class:"card-img-top img-fluid" %> 
      <% end %>
      <div class="card-body">
        <div class="row">
        <div class="col-2">
          <%= link_to user_path(plant.user) do %>
            <%= image_tag plant.user.get_profile_image(100,100), class:"mt-3 rounded-circle img-fluid" %></p>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title">
          <strong><i class="fab fa-envira"></i><span>
            <%= link_to plant_path(plant.id), class:"text-dark" do %>
              <%= plant.plant_name %>
            <% end %> 
          </span></strong>
          </p>
          
          <p class="card-text">説明：<%= plant.caption %></p>
        
          <span><i class="fas fa-user"></i> By 
            <%= link_to user_path(plant.user), class:"text-dark" do %>
              <%= plant.user.name %>
            <% end %>
          ｜ </span>
          
          <span><%= link_to "#{plant.plant_comments.count} コメント", plant_path(plant.id) %>｜</span>
    
          <!--部分テンプレートにした箇所(部分的に更新したい箇所)-->
          <span id="favorite_buttons_<%= plant.id %>">
            <%= render "favorites/btn", plant: plant %></span>
    
    <!--% if plant.favorited_by?(current_user) %>-->
    <!--    %= link_to plant_favorites_path(plant), method: :delete do %>-->
    <!--      ♥%= plant.favorites.count %>-->
    <!--    % end %>-->
    <!--% else %>-->
    <!--    %= link_to plant_favorites_path(plant), method: :post do %>-->
    <!--      ♡%= plant.favorites.count %> -->
    <!--    % end %>-->
    <!--% end %>       -->
        
        </div>
        </div>
      </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="d-flex justify-content-center"><%= paginate plants %></div>
</div>

app/views/plants/index.html.erb
<div class="text-center"><%= flash[:notice] %></div>

    <%= render 'list', plants: @plants %>

app/views/plants/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @plant.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @plant.errors.count %>件のエラーが発生しました
            </h6>
            <% @plant.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @plant do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-leaf"></i></span>
            </div>
            <%= f.text_field :plant_name, class:"form-control", placeholder:"植物名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-outline-success mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="text-center"><%= flash[:notice] %></div>

<div class="card-list-container">
  <div class="card mx-auto mt-4 shadow-lg" style="width: 600px;">
    <%= link_to plants_path do %>
      <%= image_tag @plant.get_image, class:"card-img-top img-fluid" %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@plant.user) do %>
            <%= image_tag @plant.user.get_profile_image(100,100), class:"mt-3 rounded-circle img-fluid"; %></p>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title">
          <strong><i class="fab fa-envira"></i><span>
            <%= link_to @plant.plant_name, plants_path, class:"text-dark" %>
          </span></strong></p>
             
          <p class="card-text">説明：<%= @plant.caption %></p>
          <span><i class="fas fa-user"></i> By 
            <%= link_to user_path(@plant.user), class:"text-dark" do %>
              <%= @plant.user.name %>
            <% end %>
          ｜ </span>
          
          <span><i class="fas fa-calendar"></i> <%= @plant.created_at.strftime('%Y/%m/%d') %> ｜ </span>
          
          <i class="fas fa-comment"></i>
          <!--部分テンプレートにした箇所(コメント機能非同期通信)-->
          <span class="plant_<%= @plant.id %>"><%= @plant.plant_comments.count %></span> ｜ 
          
          <!--部分テンプレートにした箇所(いいね機能非同期通信)-->
          <span id="favorite_buttons_<%= @plant.id %>">
            <%= render "favorites/btn", plant: @plant %>
          </span>
          
          <!--非同期通信前の記述-->
          <!--% if @plant.favorited_by?(current_user) %>-->
          <!--      <span>-->
          <!--      %= link_to plant_favorites_path(@plant), method: :delete do %>-->
          <!--        ♥%= @plant.favorites.count %>-->
          <!--      % end %>-->
          <!--% else %>-->
          <!--      %= link_to plant_favorites_path(@plant), method: :post do %>-->
          <!--        ♡%= @plant.favorites.count %> -->
          <!--      % end %>-->
          <!--% end %>-->
          
          <% if @plant.user == current_user %>
                <span> ｜ <%= link_to "削除", plant_path(@plant), method: :delete, "data-confirm" => "Are you sure you want to delete?" %></span>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="card-title">
      
      <!--部分テンプレートにした箇所(コメント機能非同期通信)-->
      <h4 id="plant_<%= @plant.id %>" class="mx-3"><%= @plant.plant_comments.count %>件コメント</h4>
    </div>
    <div id="plant_comments"><%= render "plant_comments/index", plant: @plant %></div>
    
    <!--非同期通信前の記述-->
    <!--% @plant.plant_comments.each do |plant_comment| %>-->
    <!--<div class="col-2">-->
    <!--  %= image_tag plant_comment.user.get_profile_image(100,100), class:"mt-3 ml-3 rounded-circle img-fluid"; %>-->
    <!--</div>-->
    <!--<div class="col-10">-->
    <!--  <div class="card-body">-->
    <!--    <p class="card-title">%= plant_comment.created_at.strftime('%Y/%m/%d') %></p>-->
    <!--    <p class="card-text">%= plant_comment.comment %></p>-->
    <!--  % if plant_comment.user == current_user %>   -->
    <!--    <p class="card-text">-->
    <!--    %= link_to "削除", plant_plant_comment_path(plant_comment.plant, plant_comment), method: :delete, class: "btn btn-danger pull-right" %> </p>      -->
    <!--  % end %> -->
    <!--  </div>-->
    <!--</div>-->
    <!--% end %>-->
    
    <div class="comments text ml-4">
      <h5 class="mt-1">コメントする</h5>
    </div>
    
    <!--非同期通信前の記述-->  
    <!--%= form_with model: [@plant, @plant_comment] do |f| %>-->
    <!--  <div class="row">-->
    <!--    <div class="col-11 mx-4 mb-4">-->
    <!--      %= f.text_area :comment, rows: '5', style: "width:102%",placeholder: "コメントをここに" %>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--  <div class="row">-->
    <!--    <div class="mx-4 mb-4 btn-text-right">      -->
    <!--      <p class="text-right">%= f.submit "送信する", class:"btn btn-lg btn-info btn-block-mt-2 float-rigth" %></p>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--% end %>-->
      
    <!--部分テンプレートにした箇所(コメント機能非同期通信)-->
    <%= render "plant_comments/form", plant: @plant, plant_comment: @pkant_comment %>
  </div> 
</div>