config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"
  
  resources :plants, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]  
    resources :plant_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    
  self.abstract_class = true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :user
  belongs_to :plant
  
end

app/models/plant.rb
class Plant < ApplicationRecord
    
  has_one_attached :image
  belongs_to :user
  has_many :plant_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :plant_name, presence: true
  validates :image, presence: true
  
  def get_image
     unless image.attached?
       file_path = Rails.root.join('app/assets/images/no_image.jpg')
       image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     image
  end 
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  
  def self.search_for(content, method)
    if method == 'perfect'
      Plant.where(plant_name: content)
    elsif method == 'forward'
      Plant.where('plant_name LIKE ?', content+'%')
    elsif method == 'backward'
      Plant.where('plant_name LIKE ?', '%' + content)
    else
      Plant.where('plant_name LIKE ?', '%' + content + '%')
    end
  end
  
  validates :plant_name,presence:true
  validates :caption,presence:true,length:{ maximum:200}
  
end

app/models/plant_comment.rb
class PlantComment < ApplicationRecord
    
  belongs_to :user
  belongs_to :plant
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User" 
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plants, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :plant_comments, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    plants_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
  def create
    @plant = Plant.find(params[:plant_id])
    favorite = current_user.favorites.new(plant_id: @plant.id) #plant => @plantへ変更
    favorite.save
    # redirect_to plant_path(plant)
  end

  def destroy
    @plant = Plant.find(params[:plant_id])
    favorite = current_user.favorites.find_by(plant_id: @plant.id) #plant => @plantへ変更
    favorite.destroy
    # redirect_to plant_path(plant)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
before_action :ensure_correct_user, only: [:update, :destroy] 

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user_id = current_user.id
    if @plant.save
       flash[:notice] = "You have created plant successfully."  
       redirect_to plants_path
    else
       render :new
    end  
  end
  
  def index
    @plants = Plant.order(created_at: :desc).page(params[:page])
  end

  def show
    @plant = Plant.find(params[:id])
    @plant_comment = PlantComment.new
  end
  
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    flash[:notice] = "plant was successfully destroyed."
    redirect_to plants_path
  end
  
  private

  def plant_params
    params.require(:plant).permit(:plant_name, :image, :caption)
  end
  
  def ensure_correct_user
    @plant = Plant.find(params[:id])
    unless @plant.user == current_user
      redirect_to plants_path
    end
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
  def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Plant.search_for(@content, @method).page(params[:page])
		end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  
  def index
    @user = current_user
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @plants = @user.plants.order(created_at: :desc).page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to plants_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/plant_comments_helper.rb
module PlantCommentsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BotanicalClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h4 class="navbar-brand text-success" href="/"><span>BotanicalClub</span>
          <i class="fas fa-leaf"></i></h4>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to plants_path, class: 'nav-link text-success' do %>
              <i class="fas fa-seedling"></i>Posts list
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_plant_path, class: 'nav-link text-success' do %>
              <i class="fas fa-seedling"></i>Post from
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-success' do %>
              <i class="fas fa-users"></i>Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-success' do %>
              <i class="fas fa-user"></i>My page
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-success' do %>
              <i class="fas fa-sign-out-alt"></i>Log out
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path,class: 'nav-link text-success' do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-success' do %>
             <i class="fas fa-link"></i>About
              <% end %>
            </li>
          
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-success' do %>
              <i class="fas fa-user-plus"></i>Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-success' do %>
              <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <div class="d-flex justify-content-end mt-1 mr-5">
        <%= render 'searches/form' %>
    </div> 
    <%= yield %>
     </main>
    <footer>
      <div class="container mt-3">
        <div class="row">
          <div class="mx-auto">
            </p>CopyRight AutumnLeaf.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>